### PR TITLE
✨ show movies from university cinema

### PR DESCRIPTION
**Pull request by BuildmodeOne**
Because the University Cinema doesn't update its website, I used a static JSON file.  [Source](https://www.instagram.com/p/Cx42ulvAjzr/)

localhost_3000_events_(iPhone 12 Pro)

### Summary
🎬📝🎭

The pull request adds cinema events to the cultural events API, using a new `movies.json` file and the OMDB API. It also fixes some club names in `clubs.json` that had typos.

> _We are the rebels of the night_
> _We watch the movies of our fight_
> _We fix the clubs with no remorse_
> _We use the `OMDB` as our source_

### Walkthrough
*  Add a new file `movies.json` with movie data for the university cinema ([link](https://github.com/neuland-ingolstadt/neuland.app/pull/337/files?diff=unified&w=0#diff-d3a0cd0944ecf573c4f14593eed9010a6dfe88720f0aaff82c245ba042596d3cR1-R38))
*  Import `movies.json` in `cl-events.js` and define constants for the OMDB API ([link](https://github.com/neuland-ingolstadt/neuland.app/pull/337/files?diff=unified&w=0#diff-d2b032cd4610ae6bf460f775603bc7057c6d73ae48b5d67c38272af790186ceaR14-R15), [link](https://github.com/neuland-ingolstadt/neuland.app/pull/337/files?diff=unified&w=0#diff-d2b032cd4610ae6bf460f775603bc7057c6d73ae48b5d67c38272af790186ceaR23-R24))
*  Implement a new function `getMovies` in `cl-events.js` that returns movie events with titles and times ([link](https://github.com/neuland-ingolstadt/neuland.app/pull/337/files?diff=unified&w=0#diff-d2b032cd4610ae6bf460f775603bc7057c6d73ae48b5d67c38272af790186ceaL141-R194))
*  Append movie events to the existing `remoteEvents` array in `getAllEventDetails` in `cl-events.js` ([link](https://github.com/neuland-ingolstadt/neuland.app/pull/337/files?diff=unified&w=0#diff-d2b032cd4610ae6bf460f775603bc7057c6d73ae48b5d67c38272af790186ceaL151-R200), [link](https://github.com/neuland-ingolstadt/neuland.app/pull/337/files?diff=unified&w=0#diff-d2b032cd4610ae6bf460f775603bc7057c6d73ae48b5d67c38272af790186ceaR214-R216))
*  Correct the club names in `clubs.json` by removing the trailing dots ([link](https://github.com/neuland-ingolstadt/neuland.app/pull/337/files?diff=unified&w=0#diff-41954d12f3122f01af52bfb68393bd51689b4816ad9f5399ae9528a53df52c46L3-R13))
*  Fix a minor spelling error in a comment in `cl-events.js` ([link](https://github.com/neuland-ingolstadt/neuland.app/pull/337/files?diff=unified&w=0#diff-d2b032cd4610ae6bf460f775603bc7057c6d73ae48b5d67c38272af790186ceaL32-R36))

### CODE REVIEW

**Review by M4GNV5 — CHANGES_REQUESTED** [review]
Since the movies JSON is static itself, wouldn't it make sense to also embed movie metadata in this JSON file? You can add a new script for retrieving those if you want. That way the events load faster and do not require yet another API key

**Comment by BuildmodeOne** [comment]
> Since the movies JSON is static itself, wouldn't it make sense to also embed movie metadata in this JSON file? You can add a new script for retrieving those if you want. That way the events load faster and do not require yet another API key

Makes total sense, maybe in the future when the university Cinema updates their Website and we scrape it, we can use the API :)

**Comment by FabianSimonGross** [comment]
Just a Information for you guys, the Uni-Cinema actually adds to the Campus-Life Newsletter, so it should be covered by the normal System. If they don't do it deal with it please like a club that does not add their events to the calender

**Comment by M4GNV5** [comment]
> Just a Information for you guys, the Uni-Cinema actually adds to the Campus-Life Newsletter, so it should be covered by the normal System. If they don't do it deal with it please like a club that does not add their events to the calender

With the information from moodle (campus life newsletter) we do not get movie metadata. Should we therefore manually filter out cinema events from the data from moodle?

**Comment by Robert27** [comment]
Is the pull request still necessary at all, since the first movie is now listed in Moodle / the api?

IMG_2218

**Pull request closed without merging**
