### PR TITLE
Updated calendar.json for winter and summer 22/23

### PR DESCRIPTION
**Pull request by FabianSimonGross**
This includes an updated calendar.json for winter and summer semesters 2022 and 2023. 
The Names have been double checked as well as the times. 

@alexhorn you said you'll take a second look on it.

### CODE REVIEW

**Comment by FabianSimonGross** [comment]
https://www.thi.de/fileadmin/daten/studienangelegenheiten/Allgemeines/Semestertermine_Studium_WS2223_und_SS23_-_05.07.2022.pdf

Used File from THI Website; Date: 2022-07-28T21:32

**Review by Robert27 — APPROVED** [review]

**Comment by alexhorn** [comment]
Data looks good, however we shouldn't remove the calendar entries from this semester because some of the entries are still ongoing (Rückmeldung, Notenbekanntgabe, Semesterferien)

**Comment by FabianSimonGross** [comment]
Will add them 

> Data looks good, however we shouldn't remove the calendar entries from this semester because some of the entries are still ongoing (Rückmeldung, Notenbekanntgabe, Semesterferien)

Will readd them quickly.

**Comment by FabianSimonGross** [comment]
[Semestertermine_Studium_WS2223_und_SS23_-_05.07.2022.pdf](https://github.com/neuland-ingolstadt/neuland.app/files/9220140/Semestertermine_Studium_WS2223_und_SS23_-_05.07.2022.pdf)

File is the said one. Just to stay secure here.

**Comment by M4GNV5** [comment]
```bash
$ curl 'https://www.thi.de/fileadmin/daten/studienangelegenheiten/Allgemeines/Semestertermine_Studium_WS2223_und_SS23_-_05.07.2022.pdf' | md5sum -
31b7472b96ff0004d56f7c6a8da7c43e  -
```

**Pull request merged**
