### PR TITLE
Removed THI-Events from Event View.

### PR DESCRIPTION
**Pull request by FabianSimonGross**

### CODE REVIEW

**Comment by M4GNV5** [comment]
This PR seems to contain 8 commits but only the last one b94f75ca528743341ed1109b8837f99de2c9a039 seems to actually change something.
We should squash this when merging or preferably create a new PR only containing the relevant commit.

**Comment by FabianSimonGross** [comment]
I do nut understand how this PR is containing 8 commits. 

How in the world. Please shquash thx

**Comment by alexhorn** [comment]
Your branch is somehow out of sync with our develop branch

**Comment by FabianSimonGross** [comment]
Closed due to broken commit structure. Will send new one when fixed.

**Pull request closed without merging**
