### PR TITLE
✨ merge meal variants; remove duplicate meals

### PR DESCRIPTION
**Pull request by BuildmodeOne**
> [!IMPORTANT]  
> Add the following to your `.env.local`:
> ```.env
>NEXT_PUBLIC_NEULAND_API_HOST=http://localhost:3000
>```

image

New Meal Page

localhost_3000_food_(iPhone 14 Pro Max) (1)
localhost_3000_food_(iPhone 14 Pro Max)

### Summary
🔄🍽️🛠️

This pull request refactors the code and data related to meal options in the rogue-thi-app. It replaces the term `variations` with `variants` for consistency and readability. It also improves the logic and translation of meal names and variants from different sources. It affects several files in the `data`, `lib`, `pages`, `public`, and `styles` directories.

> _We are the variants, we rise from the data_
> _We break the variations, we defy the schema_
> _We merge and unify, we create the plan_
> _We are the variants, we feed the hungry man_

### Walkthrough
*  Refactored the JSON data for Reimanns meals to use `variants` instead of `variations` as the property name for the different options of a meal ([link](https://github.com/neuland-ingolstadt/neuland.app/pull/362/files?diff=unified&w=0#diff-f2035e14a5200528fb71e7eda2df48d20ae060945246d49e70c682832eecb376L15-R15),[link](https://github.com/neuland-ingolstadt/neuland.app/pull/362/files?diff=unified&w=0#diff-f2035e14a5200528fb71e7eda2df48d20ae060945246d49e70c682832eecb376L43-R43),[link](https://github.com/neuland-ingolstadt/neuland.app/pull/362/files?diff=unified&w=0#diff-f2035e14a5200528fb71e7eda2df48d20ae060945246d49e70c682832eecb376L70-R70),[link](https://github.com/neuland-ingolstadt/neuland.app/pull/362/files?diff=unified&w=0#diff-f2035e14a5200528fb71e7eda2df48d20ae060945246d49e70c682832eecb376L97-R97))
*  Imported `stop-words.json` in `food-utils.js` to remove common words from meal names when merging them into variants ([link](https://github.com/neuland-ingolstadt/neuland.app/pull/362/files?diff=unified&w=0#diff-1489b1b2a6efe408765b0be482a6d535431449fd54ee39653e95777e1ef87526R5))
*  Modified `unifyFoodEntries` in `food-utils.js` to use a helper function `unifyMeal` that unifies a single meal to a common format, and added a new property `additional` to the unified meal format ([link](https://github.com/neuland-ingolstadt/neuland.app/pull/362/files?diff=unified&w=0#diff-1489b1b2a6efe408765b0be482a6d535431449fd54ee39653e95777e1ef87526L111-R198))
*  Modified `translateFallback` and `translateMeals` in `translation-utils.js` to also translate the variants of a meal, if any, using the same logic as the main meal name ([link](https://github.com/neuland-ingolstadt/neuland.app/pull/362/files?diff=unified&w=0#diff-30ad0facb2a4589591d4966d08e7dbf041a9cf06706f49d52f3844e79b9a28fbL59-R68),[link](https://github.com/neuland-ingolstadt/neuland.app/pull/362/files?diff=unified&w=0#diff-30ad0facb2a4589591d4966d08e7dbf041a9cf06706f49d52f3844e79b9a28fbR105-R113))
*  Modified `fetchPlan` in `canisius.js` and `mensa.js` to use `mergeMealvariants` from `food-utils.js` to merge meals with a similar name and same category into one meal with variants, before translating and unifying them ([link](https://github.com/neuland-ingolstadt/neuland.app/pull/362/files?diff=unified&w=0#diff-4d4c7130f7980b36f4ed88869b72865b1a5cd6a65ee107508508ebba649b3206L1-R3),[link](https://github.com/neuland-ingolstadt/neuland.app/pull/362/files?diff=unified&w=0#diff-4d4c7130f7980b36f4ed88869b72865b1a5cd6a65ee107508508ebba649b3206L136-R137),[link](https://github.com/neuland-ingolstadt/neuland.app/pull/362/files?diff=unified&w=0#diff-700273c86b0b10738155c3f03fd433af2177877ec2afc595de1ed491db71d45bL3-R6),[link](https://github.com/neuland-ingolstadt/neuland.app/pull/362/files?diff=unified&w=0#diff-700273c86b0b10738155c3f03fd433af2177877ec2afc595de1ed491db71d45bL129-R130))
*  Renamed `renderFoodVariations` to `renderFoodvariants` in `food.jsx` and changed the CSS class name `variations` to `variants` in the elements that render the meal variants, nutrition information, and prices ([link](https://github.com/neuland-ingolstadt/neuland.app/pull/362/files?diff=unified&w=0#diff-c10d0943c53eaa8dd69d7fb7a8b1e260f440b9a4a1f09bf1f7246c6c19729167L168-R176),[link](https://github.com/neuland-ingolstadt/neuland.app/pull/362/files?diff=unified&w=0#diff-c10d0943c53eaa8dd69d7fb7a8b1e260f440b9a4a1f09bf1f7246c6c19729167L238-R239),[link](https://github.com/neuland-ingolstadt/neuland.app/pull/362/files?diff=unified&w=0#diff-c10d0943c53eaa8dd69d7fb7a8b1e260f440b9a4a1f09bf1f7246c6c19729167L438-R438),[link](https://github.com/neuland-ingolstadt/neuland.app/pull/362/files?diff=unified&w=0#diff-c10d0943c53eaa8dd69d7fb7a8b1e260f440b9a4a1f09bf1f7246c6c19729167L499-R499),[link](https://github.com/neuland-ingolstadt/neuland.app/pull/362/files?diff=unified&w=0#diff-c10d0943c53eaa8dd69d7fb7a8b1e260f440b9a4a1f09bf1f7246c6c19729167L529-R533))
*  Changed the translation key `variations` to `variants` in the German and English locale files ([link](https://github.com/neuland-ingolstadt/neuland.app/pull/362/files?diff=unified&w=0#diff-f5e1d5209bf7df49a56662cbd07b82fe918ca2a6e77423191dd06bf81b9f6af7L78-R78),[link](https://github.com/neuland-ingolstadt/neuland.app/pull/362/files?diff=unified&w=0#diff-5b234807610c7f55676b9b4e964d0741d7b4196f631e08e00b5a6df8b6ab1810L77-R78))
*  Changed the CSS class name `variations` to `variants` in `Mensa.module.css` ([link](https://github.com/neuland-ingolstadt/neuland.app/pull/362/files?diff=unified&w=0#diff-8d0ecb39d3c7de5a3446411b2c28b17d26810678a5b1d89f6f12d42f67861100L75-R75))

### CODE REVIEW

**Comment by Robert27** [comment]
Another idea, could you maybe filter double soups (category soup and soups) and make them a category of soup?

IMG_3036
IMG_3037

**Comment by Robert27** [comment]
image
Two decimal places should be enough.

**Comment by BuildmodeOne** [comment]
> image
> Two decimal places should be enough. 

JavaScript 🫶🫶

**Review by Robert27 — APPROVED** [review]
Looks good too me.
Thanks for your extraordinary work. I really like the backwards compatibility and the new UI design.

**Pull request merged**
