### PR TITLE
🪲 Wrong display of current week in food.js #225

### PR DESCRIPTION
**Pull request by BuildmodeOne**
Implements the design suggested by @Robert27 in #225 

Shows days without data:

Fill days not provided by the API:

### CODE REVIEW

**Comment by Robert27** [comment]
At first glance the PR looks good, however I think the sad emoji looks a bit unprofessional. Maybe we could use these  normal food icon instead or nothing at all.

**Comment by BuildmodeOne** [comment]
> 

It was suggested by GH Copilot ;) I agree and will change that.

**Comment by BuildmodeOne** [comment]
Update: Changed icon

**Review by Robert27 — DISMISSED** [review]

**Comment by Robert27** [comment]
Maybe it is overkill, but I found two more small problems on the weekend:
When I open the Mensa tab on Saturday, it already shows me next week with the title "this week", moreover the first day (Monday) is not selected as tab. 
Screenshot 2023-03-25 at 12 06 48

**Review by Robert27 — APPROVED** [review]

**Review by Robert27 — CHANGES_REQUESTED** [review]
~~Thanks for updating the PR. However, now the bug is back if single days are missing.~~

**Review by Robert27 — APPROVED** [review]

**Pull request merged**
