### PR TITLE
Migrates Neuland API and adds Neuburg canteen

### PR DESCRIPTION
**Pull request by Robert27**
- migrates new neuland api endpoint 
- adds Neuburg canteen 
- adds more detailed parking data
- adds more charging stations

### CODE REVIEW

**Comment by alexhorn** [comment]
Honestly I'm still not convinced this is a good idea. The barrier of entry for a new developer is high enough as it is, it we migrate to GraphQL we would move the bar even higher. I'm afraid this will make it even harder to motivate new people to join the development team.

**Comment by Robert27** [comment]
Simplifying, shorten and splitting up the code as I did in this PR is the best way to lower the barrier of entry in my opinion.

**Comment by Robert27** [comment]
@alexhorn 
Simplifying, shortening and splitting the code, as I have done in this PR, is in my opinion the best way to lower the barrier to entry.
Also, the old API was not documented or typed at all, on the contrary the new API is highly user friendly with interactive query dashboard and documentation. The extra repository also makes it clearer and easier to maintain.

I also find it a bit dubious to claim that it would put people off, in the past the API has never been touched by anyone new. Because it was never necessary or the lack of documentation put everyone off.

In my opinion personal ego and pride should be put aside and instead open the way for the future, especially as the new API builds 100% on the old one and only improves it, _no work is lost_.

**Review by BuildmodeOne — DISMISSED** [review]
Looks good to me

**Comment by BuildmodeOne** [comment]
> @alexhorn Simplifying, shortening and splitting the code, as I have done in this PR, is in my opinion the best way to lower the barrier to entry. Also, the old API was not documented or typed at all, on the contrary the new API is highly user friendly with interactive query dashboard and documentation. The extra repository also makes it clearer and easier to maintain.
> 
> I also find it a bit dubious to claim that it would put people off, in the past the API has never been touched by anyone new. The reasons might be that it was never necessary or the lack of documentation put everyone off. Moreover, nothing about GraphQL is complicated, it is just a little different to query, but does not require a high level of knowledge.
> 
> In my opinion personal ego and pride should be put aside and instead open the way for the future, especially as the new API is build on top of the old one and only improves it, _no work is lost_.

I approve, the new API is no extra barrier for new people. It might even help to differentiate between the two, although I really like the API combination in NextJS, it's just not the right approach if the NextApp becomes the main app.

**Review by BuildmodeOne — DISMISSED** [review]

**Review by BuildmodeOne — APPROVED** [review]

**Comment by Robert27** [comment]
Thanks for your review.
However, I would still wait until a person with **server access**, like @alexhorn, also deployed the develop branch of the backend server and then add a new env var with the development backend URL.
Then we would have the same distinction as with the neuland.app and would later expose our main app branch less to the potential problems of the quick development changes of the backend server.

**Comment by alexhorn** [comment]
Since I am personally attacked after offering my opinion, I'm will not be reviewing this PR. I would recommend waiting for the approval of @M4GNV5.

**Comment by BuildmodeOne** [comment]
This is still a valid PR, just waiting for @M4GNV5

**Comment by BuildmodeOne** [comment]
With all personal stuff asides, how do we move forward with this PR?

**Comment by Robert27** [comment]
@alexhorn @M4GNV5

**Pull request closed without merging**
